version: "3.9"

services:
  backend:
    image: mbutner/recipe-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - scraper
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=recipes
      - SCRAPER_URL=http://scraper:5000
    secrets:
      - db_password

  scraper:
    image: mbutner/recipe-scraper:latest
    ports:
      - "5000:5000"

  frontend:
    image: mbutner/recipe-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password

volumes:
  db_data:

secrets:
  db_password:
    external: true
